//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int EstoqueId { get; set; }
        public Nullable<int> ProdutoId { get; set; }
        public Nullable<int> Qtd { get; set; }
        public Nullable<decimal> PrecoCompra { get; set; }
        public Nullable<decimal> MargemLucro { get; set; }
        public string AceitaDesconto { get; set; }
    }
}
