//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int MovimentacaoId { get; set; }
        public Nullable<int> Operacao { get; set; }
        public Nullable<int> OperadorID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
