//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendas
    {
        public int VendaId { get; set; }
        public Nullable<int> ProdutoId { get; set; }
        public Nullable<decimal> ValorVenda { get; set; }
        public Nullable<int> OperadorId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
